<template>
    <div class="intro-text-inner">
        <h3>iMuSE provides interactive visualization and analysis of mutational signatures.</h3>
        <h4>Background</h4>
        <p>Mutational signatures are distinctive patterns of somatic mutations generated by different mutational processes over the course of a lifetime <CiteP code="alexandrov2013signatures"/>. 
        These patterns have been extracted from mutation datasets using computational and mathematical techniques <CiteP code="alexandrov2013deciphering"/>.
        The concept of mutational signatures has been validated by in vitro experiments that perform knockouts of DNA repair genes and then observe that mutational signatures result <CiteP code="zou2018validating,nik2015genome"/>. 
        Many mutational signatures can be attributed to known causes or mutational processes, ranging from smoking to ultraviolet light exposure to defects in specific DNA repair pathways <CiteP code="alexandrov2016mutational,haradhvala2018distinct,helleday2014mechanisms"/>.
        Yet the origins of many other signatures remain open questions.
        
        <h4>Introduction</h4>
        iMuSE (<span class="acronym">i</span>nteractive <span class="acronym">Mu</span>tation <span class="acronym">S</span>ignature <span class="acronym">E</span>xplorer) is a web-based mutation data browser that enables exploration of mutational signatures, clinical data, and mutation density. 
        This tool allows users to choose sequencing project datasets by cancer type, as well as mutational signature combinations (of which can be selected based on cancer-type-specific presets) before plotting this data. 
        Web-based interactive visualizations allow for exploration across datasets and features in a way that is accessible and fast. 
        Data exploration through these visualizations can be used to make initial inferences that lead to further statistical analysis, or, alternatively, can be used to verify and communicate relationships found through prior analysis. 
        iMuSE is developed by the <a href="https://lrgr.io" target="_blank">Leiserson Research Group</a>.

        <h4>Getting Started</h4>
        <p>
            To begin, select sample cohorts and mutational signatures of interest. 
            Signatures can be selected based on cancer types in which they are present.
            Signatures will be auto-selected if none have been manually selected and the selected samples map to a single cancer type.
        </p>

        <h4>References</h4>
        <div v-for="(citation, index) in bibliography" :key="citation.code" :id="'bib-' + (index+1)" class="reference">
            <div class="reference-index">{{ (index+1) }}. </div>
            <div class="reference-details">
                <span v-for="(author, index) in citation.authors" :key="author">{{ author }}<span v-if="index != citation.authors.length-1">, </span></span>. 
                {{ citation.title }}. 
                <span class="journal">{{ citation.journal }}</span>.
                {{ citation.volume }}({{ citation.number }}):{{ citation.pages }}, {{ citation.year }}.
            </div>
        </div>

        <span class="intro-modal-link" @click="showModal">Open Source</span>

        <div class="modal" v-show="modalVisible">
            <div class="modal-inner">
                <span class="modal-close" @click="closeModal">Close</span>
                <div class="oss-modal">
                    <h3>Open Source</h3>
                    <div>
                        This web application includes code from the following modules.
                        <h4>MIT</h4>
                        <a href="https://www.npmjs.com/package/colorjoe" target="_blank">colorjoe</a> &copy; Evan Juho Veps&#228;l&#228;inen<br>
                        <a href="https://www.npmjs.com/package/json2csv" target="_blank">json2csv</a> &copy; Mirco Zeiss<br>
                        <a href="https://www.npmjs.com/package/lodash" target="_blank">lodash</a> &copy; JS Foundation<br>
                        <a href="https://www.npmjs.com/package/vue" target="_blank">vue</a> &copy; Yuxi (Evan) You<br>
                        <a href="https://www.npmjs.com/package/vue-resize" target="_blank">vue-resize</a> &copy; Guillaume Chau<br>
                        <a href="https://www.npmjs.com/package/vuex" target="_blank">vuex</a> &copy; Evan You<br>

                        <h4>BSD-3-Clause</h4>
                        <a href="https://www.npmjs.com/package/d3" target="_blank">d3</a> &copy; Mike Bostock<br>

                        <h4>ISC</h4>
                        <a href="https://www.npmjs.com/package/d3-delaunay" target="_blank">d3-delaunay</a> &copy; Observable, Inc.<br>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-background" v-show="modalVisible" @click="closeModal"></div>
    </div>
</template>

<script>
import { mapGetters } from 'vuex';
import CiteP from './CiteP.vue';

export default {
  name: 'IntroText',
  components: {
      CiteP
  },
  data() {
      return {
          modalVisible: false
      };
  },
  computed: {
      ...mapGetters([
          'bibliography'
      ])
  },
  methods: {
      closeModal() {
          this.modalVisible = false;
      },
      showModal() {
          this.modalVisible = true;
      }
  }
}
</script>

<style scoped lang="scss">
@import './../style/variables.scss';
@import './../style/modal.scss';

.intro-text-inner {
    text-align: justify;
    .acronym {
        font-weight: bold;
    }
    .journal {
        font-style: italic;
    }
}
.reference {
    display: flex;
    flex-direction: column wrap;
    margin-bottom: 10px;
    .reference-index {
        padding-right: 10px;
    }
}

.oss-modal {
    padding: 1rem;
    h3 {
        margin-top: 0;
    }
    h4 {
        margin-bottom: 0;
    }
    a {
        color: rgb(65, 120, 223);
        text-decoration: none;
    }
}

.intro-modal-link {
    margin-top: 1rem;
    margin-bottom: 1rem;
    display: inline-block;
    text-decoration: underline;
    cursor: pointer;
}

</style>
