<template>
    <div>
        <span class="explorer-control-title">Session</span>
        <button @click="startSession" v-if="!isEmptySession">Start</button>
        <button @click="whatSession">What is this?</button>

        <div class="modal" v-if="modalVisible">
            <div class="modal-inner">
                <span class="modal-close" @click="closeModal">Close</span>
                <div class="start-session-options-wrapper" v-if="startSessionModalVisible">
                    <h3>Session</h3>
                    <p>Use the following session ID to access the current session:</p>
                    <div class="conn-id" v-if="currSessionID.length > 0">
                        <pre>{{ currSessionID }}</pre>
                    </div>
                    <VSpinner v-if="isLoading" class="spinner" />
                </div>
                <div class="start-session-options-wrapper" v-if="whatSessionModalVisible">
                    <h3>What is an ExploSig session?</h3>
                    <p>
                        An ExploSig session can be used to send your data to ExploSig for visualization. Using the <a href="https://pypi.org/project/explosig-connect/" target="_blank">explosig-connect</a> Python package, data can be sent from any Python environment.
                    </p>

                    <p>
                        ExploSig supports two types of sessions, described in the table below:
                    </p>
                    <table id="session-desc-table">
                        <thead>
                            <tr>
                                <th>"Configured" Session</th>
                                <th>"Empty" Session</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    Started from within ExploSig after selecting samples, signatures, genes, and clinical variables (a particular data "configuration").
                                    Because this session is associated with a configuration, the corresponding data can be obtained from within Python.

                                    A session ID generated by ExploSig must be passed as a parameter to the <strong>connect()</strong> function.

                                    <span v-if="isSession && !isEmptySession">
                                        <br><br>
                                        <strong>You are currently in a configured session.</strong>
                                    </span>
                                </td>
                                <td>
                                    Started by executing the <strong>connect()</strong> function without passing a session ID parameter.
                                    All data to be visualized must be sent to ExploSig.

                                    <span v-if="isSession && isEmptySession">
                                        <br><br>
                                        <strong>You are currently in an empty session.</strong>
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <h4>Current Limitations</h4>
                    <li>Sending data to a session clears the history stack because previous history actions could potentially refer to incorrect data.</li>
                    <li>Once a session has been started, "export" URLs cannot be generated because exported history actions do not store data updates and therefore could potentially refer to incorrect data.</li>
                    <li>Do not send sensitive data over an ExploSig session. If you are concerned about security, please run ExploSig locally using <a href="https://github.com/lrgr/explosig-docker" target="_blank">explosig-docker</a>.</li>
                </div>
            </div>
        </div>
        <div class="modal-background" v-show="modalVisible" @click="closeModal"></div>
    </div>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex';
import API from './../api.js';

import VSpinner from './VSpinner.vue';

export default {
    name: 'SessionButtons',
    components: {
        VSpinner,
    },
    data() {
        return {
            currSessionID: "",
            isLoading: false,
            modalVisible: false,
            startSessionModalVisible: false,
            whatSessionModalVisible: false,
        };
    },
    computed: {
        ...mapGetters([
            'getConfig',
            'getScale',
            'getData',
            'getStack',
            'getStratification',
            'getDataKeys',
            'isSession',
            'isEmptySession'
        ])
    },
    methods: {
        closeModal() {
            this.modalVisible = false;
            this.startSessionModalVisible = false;
            this.whatSessionModalVisible = false;
        },
        startSession() {
            this.isLoading = true;
            this.modalVisible = true;
            this.startSessionModalVisible = true;

            if(this.currSessionID.length === 0) {
                // No session ID exists yet, so request one.
                let state = {
                    "config": this.getConfig().export()
                };
                API.startSession(state).then((data) => {
                    this.isLoading = false;
                    this.currSessionID = data['session_id'];

                    API.connectSession(this.currSessionID);
                    this.setSession({ isSession: true, isEmptySession: false, sessionId: this.currSessionID });
                });
            } else {
                // Already have a session ID.
                this.isLoading = false;
            }
        },
        whatSession() {
            this.isLoading = true;
            this.modalVisible = true;
            this.whatSessionModalVisible = true;
        },
        ...mapMutations([
            'setSession',
        ])
    }
}
</script>

<style scoped lang="scss">
@import './../style/variables.scss';
@import './../style/modal.scss';

.start-session-options-wrapper {
    padding: 1rem;
    overflow-y: scroll;
    height: 80vh;
    box-sizing: border-box;
    h3 {
        margin-top: 0;
    }
    .conn-id {
        background-color: $color-lgreen;
        padding: 0.2rem;
        font-size: 1.1rem;
        text-align: center;
        border: 1px solid $color-gray;
        color: $color-darkgray;
        border-radius: 3px;
    }
}

#session-desc-table {
    border-collapse: collapse;
    border: 1px solid black;
    th, td {
        padding: 15px;
        text-align: left;
        border: 1px solid black;
    }
    tbody > tr > td {
        width: 50%;
    }
}

</style>
